apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 2
  matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
  template:
    spec:
      containers:
      - name: nginx
        image: ellisjoe611/grooming:latest
        ports:
        - containerPort: 81